
* Interactive browser

The goal of this package is to be able to control your browser through common actions (switch tabs, close tabs, open tabs from history link, copy a url, send the url to embark-become...) using emacs built-in functionnalities.

This package currently introduces the following commands :
- =browser-tab-select-tab-by-name=
- =browser-tab-close-tab-by-name=

This package is inspired by the [[https://github.com/kevinmorio/rofi-switch-browser-tabs][Rofi Switch Browser Tabs]] scripts, but aspires to have broader functionalities, more integrated with Emacs. It relies on the =completing-read= built-in interface, and thus benefits grealty from integration with =consult=, =marginalia=, and =vertico=. For now, it only implements the Chromium Developer Protocol script, which should soon be implemented by firefox-based browsers. PR are welcome for other protocols!

** Chromium Developer Protocol

*** Usage
1. Install the package using your favorite package manager.
2. Run your browser with the option =--remote-debugging-port=9222=.
3. Use the commands mentionned above in Emacs.

**** Packaging status
***** TODO Guix
***** TODO MELPA

** Embark functionalities

After loading the file =interactive-browser-embark.el=, you can also select commands once a tab is selected, in case you change your mind.
